# Generated by Django 6.0.2 on 2026-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='github_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
